export const T = {
    appName: { en: "FluentUp", ar: "فلوينت أب" },
    home: { en: "Home", ar: "الرئيسية" },
    vocab: { en: "Vocabulary", ar: "المفردات" },
    shadowing: { en: "Shadowing", ar: "المحاكاة" },
    quizzes: { en: "Quizzes", ar: "اختبارات" },
    progress: { en: "Progress", ar: "التقدم" },
    stories: { en: "Stories", ar: "قصص" },
    greeting: { en: "Good Morning! 🌟", ar: "صباح الخير! 🌟" },
    greetingEve: { en: "Good Evening! 🌙", ar: "مساء الخير! 🌙" },
    wordOfDay: { en: "Word of the Day", ar: "كلمة اليوم" },
    streak: { en: "Day Streak", ar: "أيام متتالية" },
    xpToday: { en: "XP Today", ar: "نقاط اليوم" },
    dailyGoal: { en: "Daily Goal: 100 XP", ar: "الهدف اليومي: 100 نقطة" },
    startSession: { en: "Start Session", ar: "ابدأ الجلسة" },
    exitSession: { en: "Exit Session", ar: "خروج من الجلسة" },
    level: { en: "Level", ar: "المستوى" },
    reviewDue: { en: "Due for Review", ar: "للمراجعة" },
    iKnowIt: { en: "I Know It", ar: "أعرفها" },
    reviewAgain: { en: "Review Again", ar: "راجعها مجدداً" },
    hearExample: { en: "Hear Example", ar: "استمع للمثال" },
    record: { en: "Record", ar: "تسجيل" },
    stop: { en: "Stop", ar: "إيقاف" },
    playOriginal: { en: "Original", ar: "الأصلي" },
    playYours: { en: "Your Voice", ar: "صوتك" },
    quizMultiple: { en: "Multiple Choice", ar: "خيارات متعددة" },
    quizFill: { en: "Fill in the Blank", ar: "أكمل الفراغ" },
    quizScore: { en: "Your Score", ar: "نتيجتك" },
    achievements: { en: "Achievements", ar: "الإنجازات" },
    wordsLearned: { en: "Words Learned", ar: "الكلمات المتعلمة" },
    totalXp: { en: "Total XP", ar: "إجمالي النقاط" },
    aiGeneratorTitle: { en: "✨ AI Vocab Builder", ar: "✨ منشئ المفردات الذكي" },
    aiTopicPrompt: { en: "What topic do you want to learn? (e.g., Space, Baking)", ar: "ما الموضوع الذي تريد تعلمه؟ (مثال: الفضاء، الطبخ)" },
    generateBtn: { en: "Generate", ar: "توليد" },
    generatingBtn: { en: "Generating...", ar: "جاري التوليد..." },
    explainGrammar: { en: "✨ Explain Grammar", ar: "✨ شرح القواعد" },
    levelPacks: { en: "Smart Level Packs (Infinite Words)", ar: "حزم المستويات الذكية (كلمات لا نهائية)" },
    packBeginner: { en: "Beginner (+10)", ar: "مبتدئ (+10)" },
    packIntermediate: { en: "Intermediate (+10)", ar: "متوسط (+10)" },
    packAdvanced: { en: "Advanced (+10)", ar: "متقدم (+10)" },
    shadowPacks: { en: "Smart Sentence Packs", ar: "حزم الجمل الذكية" },
    shadowFilterAll: { en: "All Levels", ar: "كل المستويات" },
    shadowCompleted: { en: "Completed", ar: "مكتمل" },
    shadowRemaining: { en: "Remaining", ar: "متبقي" },
    shadowSentencesCompleted: { en: "sentences completed", ar: "جملة مكتملة" },
    browseSentences: { en: "Browse Sentences", ar: "تصفح الجمل" },
    nextSentence: { en: "Next Sentence", ar: "الجملة التالية" },
    finishSession: { en: "Finish Session", ar: "إنهاء الجلسة" },
    back: { en: "Back", ar: "عودة" },
    tapToFlip: { en: "Tap to flip", ar: "اضغط للقلب" },
    didNotKnow: { en: "Don't Know", ar: "لا أعرف" },
    knewIt: { en: "I Knew It", ar: "كنت أعرفها" },
    searchPlaceholder: { en: "Search words...", ar: "بحث عن كلمات..." },
    filterAll: { en: "All Levels", ar: "كل المستويات" },
    noWordsFound: { en: "No words found matching your search.", ar: "لم يتم العثور على كلمات مطابقة لبحثك." },
    loadMore: { en: "Load More", ar: "تحميل المزيد" },
    aiTutorTitle: { en: "AI English Tutor", ar: "معلم اللغة الإنجليزية الذكي" },
    aiTutorDesc: { en: "Practice speaking English naturally. I will help you improve!", ar: "تدرب على التحدث بالإنجليزية بشكل طبيعي. سأساعدك على التحسن!" },
    listening: { en: "Listening...", ar: "جاري الاستماع..." },
    thinking: { en: "Thinking...", ar: "جاري التفكير..." },
    tapToTalk: { en: "Tap to Speak", ar: "اضغط للتحدث" },
    stopTalking: { en: "Stop Talking", ar: "إيقاف التحدث" },
    chatInputPlaceholder: { en: "Type your message here...", ar: "اكتب رسالتك هنا..." },
    send: { en: "Send", ar: "إرسال" },
    newChat: { en: "New Chat", ar: "محادثة جديدة" },
    chatHistory: { en: "Chat History", ar: "سجل المحادثات" },
    classicLibrary: { en: "Classic Library", ar: "المكتبة الكلاسيكية" },
    publicDomain: { en: "Public Domain", ar: "ملك عام" },
    readStory: { en: "Read Story", ar: "اقرأ القصة" },
    aboutAuthor: { en: "About the Author", ar: "عن الكاتب" },
    storyCompleted: { en: "Story Completed!", ar: "تم إكمال القصة!" },
    discoverMore: { en: "Discover More Classics", ar: "اكتشف المزيد من الكلاسيكيات" },
};

const generateWords = () => {
    const bases = [
        // BEGINNER (A1/A2)
        {en: 'water', ar: 'ماء', ph: '/ˈwɔːtər/', em: '💧', exEn: 'I drink water.', exAr: 'أشرب الماء.', lvl: 'Beginner', cat: 'Daily Life'},
        {en: 'house', ar: 'منزل', ph: '/haʊs/', em: '🏠', exEn: 'This is my house.', exAr: 'هذا منزلي.', lvl: 'Beginner', cat: 'Daily Life'},
        {en: 'friend', ar: 'صديق', ph: '/frɛnd/', em: '🤝', exEn: 'He is my friend.', exAr: 'إنه صديقي.', lvl: 'Beginner', cat: 'Daily Life'},
        {en: 'time', ar: 'وقت', ph: '/taɪm/', em: '⏰', exEn: 'What time is it?', exAr: 'كم الوقت؟', lvl: 'Beginner', cat: 'Daily Life'},
        {en: 'money', ar: 'مال', ph: '/ˈmʌni/', em: '💵', exEn: 'I need money.', exAr: 'أحتاج إلى المال.', lvl: 'Beginner', cat: 'Daily Life'},
        {en: 'doctor', ar: 'طبيب', ph: '/ˈdɒktər/', em: '👨⚕️', exEn: 'See a doctor.', exAr: 'راجع طبيباً.', lvl: 'Beginner', cat: 'Health'},
        {en: 'food', ar: 'طعام', ph: '/fuːd/', em: '🍔', exEn: 'I love this food.', exAr: 'أحب هذا الطعام.', lvl: 'Beginner', cat: 'Food'},
        {en: 'happy', ar: 'سعيد', ph: '/ˈhæpi/', em: '😊', exEn: 'I am very happy.', exAr: 'أنا سعيد جداً.', lvl: 'Beginner', cat: 'Emotions'},
        {en: 'book', ar: 'كتاب', ph: '/bʊk/', em: '📖', exEn: 'Read a book.', exAr: 'اقرأ كتاباً.', lvl: 'Beginner', cat: 'Academic'},
        {en: 'car', ar: 'سيارة', ph: '/kɑːr/', em: '🚗', exEn: 'I drive a car.', exAr: 'أنا أقود سيارة.', lvl: 'Beginner', cat: 'Travel'},
        
        // INTERMEDIATE (B1/B2)
        {en: 'meeting', ar: 'اجتماع', ph: '/ˈmiːtɪŋ/', em: '💼', exEn: 'We have an important meeting.', exAr: 'لدينا اجتماع مهم.', lvl: 'Intermediate', cat: 'Work'},
        {en: 'project', ar: 'مشروع', ph: '/ˈpɒdʒɛkt/', em: '📊', exEn: 'This is a new project.', exAr: 'هذا مشروع جديد.', lvl: 'Intermediate', cat: 'Work'},
        {en: 'deadline', ar: 'موعد نهائي', ph: '/ˈdɛdlaɪn/', em: '⏳', exEn: 'We must meet the deadline.', exAr: 'يجب أن نلتزم بالموعد النهائي.', lvl: 'Intermediate', cat: 'Work'},
        {en: 'passenger', ar: 'مسافر', ph: '/ˈpæsɪndʒər/', em: '🧳', exEn: 'The passenger is waiting.', exAr: 'المسافر ينتظر.', lvl: 'Intermediate', cat: 'Travel'},
        {en: 'destination', ar: 'وجهة', ph: '/ˌdɛstɪˈneɪʃn/', em: '📍', exEn: 'Paris is our destination.', exAr: 'باريس هي وجهتنا.', lvl: 'Intermediate', cat: 'Travel'},
        {en: 'delicious', ar: 'لذيذ', ph: '/dɪˈlɪʃəs/', em: '🤤', exEn: 'The meal was delicious.', exAr: 'كانت الوجبة لذيذة.', lvl: 'Intermediate', cat: 'Food'},
        {en: 'software', ar: 'برمجيات', ph: '/ˈsɔːftwɛər/', em: '💿', exEn: 'Update the software.', exAr: 'حدث البرمجيات.', lvl: 'Intermediate', cat: 'Technology'},
        {en: 'environment', ar: 'بيئة', ph: '/ɪnˈvaɪrənmənt/', em: '🌍', exEn: 'Protect the environment.', exAr: 'احمِ البيئة.', lvl: 'Intermediate', cat: 'Daily Life'},

        // ADVANCED (C1/C2)
        {en: 'mitigate', ar: 'يخفف / يقلل', ph: '/ˈmɪtɪɡeɪt/', em: '📉', exEn: 'We need to mitigate the risks.', exAr: 'نحتاج إلى التخفيف من المخاطر.', lvl: 'Advanced', cat: 'Work'},
        {en: 'ubiquitous', ar: 'شائع / موجود في كل مكان', ph: '/juːˈbɪkwɪtəs/', em: '🌐', exEn: 'Smartphones are ubiquitous today.', exAr: 'الهواتف الذكية موجودة في كل مكان اليوم.', lvl: 'Advanced', cat: 'Technology'},
        {en: 'lucrative', ar: 'مربح', ph: '/ˈluːkrətɪv/', em: '💸', exEn: 'It is a highly lucrative business.', exAr: 'إنه عمل مربح للغاية.', lvl: 'Advanced', cat: 'Work'},
        {en: 'pragmatic', ar: 'عملي / واقعي', ph: '/præɡˈmætɪk/', em: '🛠️', exEn: 'We need a pragmatic approach.', exAr: 'نحتاج إلى نهج عملي.', lvl: 'Advanced', cat: 'Work'},
        {en: 'eloquent', ar: 'فصيح / بليغ', ph: '/ˈɛləkwənt/', em: '🗣️', exEn: 'She gave an eloquent speech.', exAr: 'ألقت خطاباً بليغاً.', lvl: 'Advanced', cat: 'Daily Life'}
    ];
    return bases.map((b, i) => ({
        id: i + 1, english: b.en, arabic: b.ar, phonetic: b.ph, emoji: b.em,
        example_en: b.exEn, example_ar: b.exAr, category: b.cat, level: b.lvl,
        learned: false, repetition_count: 0, next_review: null
    }));
};

export const INITIAL_WORDS = generateWords();

export const SENTENCES = [
    // Beginner
    { id: 1, english: "Good morning! How are you doing today?", arabic: "صباح الخير! كيف حالك اليوم؟", words: ["Good", "morning!", "How", "are", "you", "doing", "today?"], topic: "Greetings", level: "Beginner" },
    { id: 2, english: "I would like to order a cup of coffee, please.", arabic: "أود أن أطلب كوباً من القهوة، من فضلك.", words: ["I", "would", "like", "to", "order", "a", "cup", "of", "coffee,", "please."], topic: "Shopping", level: "Beginner" },
    { id: 3, english: "Excuse me, where is the nearest train station?", arabic: "معذرة، أين أقرب محطة قطار؟", words: ["Excuse", "me,", "where", "is", "the", "nearest", "train", "station?"], topic: "Travel", level: "Beginner" },
    { id: 4, english: "My name is Sarah, nice to meet you.", arabic: "اسمي سارة، سررت بلقائك.", words: ["My", "name", "is", "Sarah,", "nice", "to", "meet", "you."], topic: "Introductions", level: "Beginner" },
    { id: 5, english: "Could you please speak a little slower?", arabic: "هل يمكنك التحدث ببطء قليلاً من فضلك؟", words: ["Could", "you", "please", "speak", "a", "little", "slower?"], topic: "Learning", level: "Beginner" },
    
    // Intermediate
    { id: 16, english: "Nice to meet you. I am looking forward to working together.", arabic: "سعدت بلقائك. أتطلع للعمل معاً.", words: ["Nice", "to", "meet", "you.", "I", "am", "looking", "forward", "to", "working", "together."], topic: "Work", level: "Intermediate" },
    { id: 17, english: "My flight departs from terminal three at five PM.", arabic: "تغادر رحلتي من المبنى رقم ثلاثة في الساعة الخامسة مساءً.", words: ["My", "flight", "departs", "from", "terminal", "three", "at", "five", "PM."], topic: "Travel", level: "Intermediate" },
    
    // Advanced
    { id: 31, english: "I think we need to rethink our current strategy.", arabic: "أعتقد أننا بحاجة إلى إعادة التفكير في استراتيجيتنا الحالية.", words: ["I", "think", "we", "need", "to", "rethink", "our", "current", "strategy."], topic: "Work", level: "Advanced" },
    { id: 32, english: "The weather has been quite unpredictable lately, hasn't it?", arabic: "كان الطقس متقلباً جداً مؤخراً، أليس كذلك؟", words: ["The", "weather", "has", "been", "quite", "unpredictable", "lately,", "hasn't", "it?"], topic: "Small Talk", level: "Advanced" }
];

export const PUBLIC_DOMAIN_STORIES = [
    {
        id: 1,
        isInitial: true,
        title: "The Boy Who Cried Wolf",
        author: "Aesop",
        year: "6th Century BC",
        level: "Beginner",
        cover: "https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=800&q=80",
        description: "A famous fable about the importance of honesty and the consequences of lying.",
        descriptionAr: "خرافة شهيرة عن أهمية الصدق وعواقب الكذب.",
        sentences: [
            { en: "There was once a young shepherd boy who looked after his sheep on the hillside.", ar: "كان هناك يوماً صبي راعي صغير يرعى أغنامه على سفح التل." },
            { en: "The boy found it very quiet and lonely, and he was often bored.", ar: "كان الصبي يجد المكان هادئاً ومنعزلاً جداً، وكان غالباً ما يشعر بالملل." },
            { en: "One day, he decided to have some fun and play a trick on the villagers.", ar: "ذات يوم، قرر أن يستمتع قليلاً ويمزح مع أهل القرية." },
            { en: "He climbed a tree and shouted as loud as he could, \"Wolf! Wolf! A wolf is chasing the sheep!\"", ar: "تسلق شجرة وصرخ بأعلى صوته: \"ذئب! ذئب! ذئب يطارد الأغنام!\"" },
            { en: "The villagers heard him and ran up the hill to help him drive the wolf away.", ar: "سمعه القرويون وركضوا إلى التل لمساعدته في طرد الذئب." },
            { en: "When they arrived, there was no wolf, and the boy laughed at their angry faces.", ar: "عندما وصلوا، لم يكن هناك ذئب، فضحك الصبي على وجوههم الغاضبة." },
            { en: "\"There is no wolf,\" he said, \"I was just playing a game!\"", ar: "قال: \"لا يوجد ذئب، كنت فقط ألعب لعبة!\"" },
            { en: "Later, a real wolf actually came out of the forest and began to attack the sheep.", ar: "لاحقاً، خرج ذئب حقيقي بالفعل من الغابة وبدأ في مهاجمة الأغنام." },
            { en: "Terrified, the boy cried for help again, \"Wolf! Wolf! Please help me!\"", ar: "صرخ الصبي مرعوباً طلباً للمساعدة مرة أخرى: \"ذئب! ذئب! من فضلك ساعدني!\"" },
            { en: "But the villagers thought he was tricking them again, so they stayed in the village.", ar: "لكن القرويين اعتقدوا أنه يخدعهم مرة أخرى، فبقوا في القرية." },
            { en: "At sunset, the boy came home alone, crying because he had lost his sheep.", ar: "عند غروب الشمس، عاد الصبي إلى المنزل بمفرده، باكياً لأنه فقد أغنامه." },
            { en: "\"A liar will not be believed,\" the old man said, \"even when he speaks the truth.\"", ar: "قال الرجل العجوز: \"الكاذب لن يصدق، حتى عندما يقول الحقيقة.\"" }
        ]
    },
    {
        id: 5,
        isInitial: true,
        title: "The Lion and the Mouse",
        author: "Aesop",
        year: "6th Century BC",
        level: "Beginner",
        cover: "https://images.unsplash.com/photo-1546182990-dffeafbe841d?auto=format&fit=crop&w=800&q=80",
        description: "A small act of kindness can lead to a great reward.",
        descriptionAr: "فعل صغير من اللطف يمكن أن يؤدي إلى مكافأة عظيمة.",
        sentences: [
            { en: "A Lion was asleep in the sun one day when a little Mouse ran over his nose.", ar: "كان هناك أسد نائماً في الشمس ذات يوم عندما ركض فأر صغير على أنفه." },
            { en: "The Lion woke up and caught the Mouse with his huge paw.", ar: "استيقظ الأسد وأمسك بالفأر بمخلبه الضخم." },
            { en: "\"Please don't eat me!\" cried the Mouse. \"If you let me go, I will help you one day.\"", ar: "صرخ الفأر: \"من فضلك لا تأكلني! إذا تركتني أذهب، فسأساعدك يوماً ما.\"" },
            { en: "The Lion laughed at the idea of a tiny Mouse helping a King of Beasts.", ar: "ضحك الأسد من فكرة أن فأراً صغيراً يساعد ملك الوحوش." },
            { en: "However, the Lion was in a good mood, so he let the Mouse go.", ar: "ومع ذلك، كان الأسد في مزاج جيد، فترك الفأر يذهب." },
            { en: "A few days later, the Lion was caught in a hunter's net.", ar: "بعد بضعة أيام، وقع الأسد في شبكة صياد." },
            { en: "He roared with anger and struggled to get free, but the ropes were too strong.", ar: "زأر بغضب وحاول التحرر، لكن الحبال كانت قوية جداً." },
            { en: "The little Mouse heard the Lion's roar and ran to see what was wrong.", ar: "سمع الفأر الصغير زئير الأسد وركض ليرى ما المشكلة." },
            { en: "She immediately began to gnaw at the ropes with her sharp little teeth.", ar: "بدأت على الفور في قرض الحبال بأسنانها الصغيرة الحادة." },
            { en: "Soon the Lion was free. \"You see,\" said the Mouse, \"even a little Mouse can help a Lion!\"", ar: "سرعان ما أصبح الأسد حراً. قال الفأر: \"أرأيت، حتى الفأر الصغير يمكنه مساعدة أسد!\"" }
        ]
    },
    {
        id: 2,
        isInitial: true,
        title: "The Little Match Girl",
        author: "Hans Christian Andersen",
        year: "1845",
        level: "Intermediate",
        cover: "https://images.unsplash.com/photo-1418985991508-e473a24ebb4f?auto=format&fit=crop&w=800&q=80",
        description: "A touching story of hope and vision on a freezing winter night.",
        descriptionAr: "قصة مؤثرة عن الأمل والرؤى في ليلة شتاء قارسة.",
        sentences: [
            { en: "It was terribly cold; it snowed and was already almost dark.", ar: "كان البرد قارساً؛ كانت تثلج والدنيا تكاد تظلم." },
            { en: "A poor little girl, bareheaded and barefoot, walked through the streets.", ar: "سارت فتاة صغيرة فقيرة، حافية الرأس والقديمين، في الشوارع." },
            { en: "She carried a quantity of matches in an old apron.", ar: "كانت تحمل كمية من أعواد الثقاب في مئزر قديم." },
            { en: "She had not sold any all day, and no one had given her a single penny.", ar: "لم تبع أي شيء طوال اليوم، ولم يعطها أحد قرشاً واحداً." },
            { en: "Shivering with cold and hunger, she crept along.", ar: "كانت ترتجف من البرد والجوع وهي تسير ببطء." },
            { en: "She lighted a match, and it burned with a warm, bright flame.", ar: "أشعلت عود ثقاب، فاحترق بلهب دافئ ومشرق." },
            { en: "Suddenly, she saw a grand iron stove with brass ornaments.", ar: "فجأة، رأت مدفأة حديدية ضخمة بزخارف نحاسية." },
            { en: "She stretched out her feet to warm them also, but the flame went out.", ar: "مدت قدميها لتدفئتهما أيضاً، لكن اللهب انطفأ." },
            { en: "She rubbed another match against the wall, and it became bright.", ar: "حكت عود ثقاب آخر على الحائط، فأصبح مشرقاً." },
            { en: "In the bright light, she saw her grandmother, so gentle and so loving.", ar: "في الضوء الساطع، رأت جدتها، اللطيفة جداً والمحبة جداً." },
            { en: "\"Grandmother!\" cried the little girl. \"Take me with you!\"", ar: "صرخت الفتاة الصغيرة: \"جدتي! خذيني معك!\"" },
            { en: "In the morning, people found the little girl with a smile on her face.", ar: "في الصباح، وجد الناس الفتاة الصغيرة وعلى وجهها ابتسامة." }
        ]
    },
    {
        id: 4,
        isInitial: true,
        title: "The Selfish Giant",
        author: "Oscar Wilde",
        year: "1888",
        level: "Intermediate",
        cover: "https://images.unsplash.com/photo-1622321459297-f03ba30283ea?auto=format&fit=crop&w=800&q=80",
        description: "A beautiful tale of redemption and the joy of sharing.",
        descriptionAr: "حكاية جميلة عن الخلاص وبهجة المشاركة.",
        sentences: [
            { en: "Every afternoon, the children used to go and play in the Giant's beautiful garden.", ar: "كل بعد ظهر، اعتاد الأطفال الذهاب واللعب في حديقة العملاق الجميلة." },
            { en: "It was a large lovely garden, with soft green grass and peach trees.", ar: "كانت حديقة جميلة وكبيرة، بها عشب أخضر ناعم وأشجار خوخ." },
            { en: "One day the Giant came back and saw the children playing in his garden.", ar: "ذات يوم عاد العملاق ورأى الأطفال يلعبون في حديقته." },
            { en: "\"What are you doing here?\" he shouted in a very gruff voice, and the children ran away.", ar: "صرخ بصوت خشن جداً: \"ماذا تفعلون هنا؟\"، فهرب الأطفال." },
            { en: "He built a high wall all round it, and put up a notice-board: TRESPASSERS WILL BE PROSECUTED.", ar: "بنى جسوراً عالية حولها، ووضع لوحة إعلانات: سيتم مقاضاة المتسللين." },
            { en: "Then the Spring came, but in the garden of the Selfish Giant it was still Winter.", ar: "ثم جاء الربيع، ولكن في حديقة العملاق الأناني كان لا يزال الشتاء." },
            { en: "The birds did not care to sing in it as there were no children, and the trees forgot to blossom.", ar: "لم تهتم الطيور بالغناء فيها لعدم وجود أطفال، ونسيت الأشجار أن تزهر." },
            { en: "One morning the Giant heard some lovely music. It was a little bird singing outside his window.", ar: "ذات صباح سمع العملاق موسيقى جميلة. كان طائراً صغيراً يغني خارج نافذته." },
            { en: "He looked out and saw a hole in the wall, and the children had crept in.", ar: "نظر للخارج ورأى ثقباً في الجدار، وقد تسلل الأطفال للداخل." },
            { en: "In every tree that he could see there was a little child.", ar: "في كل شجرة كان يراها كان هناك طفل صغير." },
            { en: "\"How selfish I have been!\" he said; \"now I know why the Spring would not come here.\"", ar: "قال: \"كم كنت أنانياً! الآن أعرف لماذا لم يأتِ الربيع إلى هنا.\"" },
            { en: "He knocked down the wall, and his garden became a paradise for children forever.", ar: "هدم الجدار، وأصبحت حديقته جنة للأطفال إلى الأبد." }
        ]
    },
    {
        id: 3,
        isInitial: true,
        title: "The Gift of the Magi",
        author: "O. Henry",
        year: "1905",
        level: "Advanced",
        cover: "https://images.unsplash.com/photo-1512389142860-9c449e58a543?auto=format&fit=crop&w=800&q=80",
        description: "A classic holiday tale of selfless love and the true meaning of giving.",
        descriptionAr: "حكاية عطلة كلاسيكية عن الحب غير الأناني والمعنى الحقيقي للعطاء.",
        sentences: [
            { en: "One dollar and eighty-seven cents. That was all. And the next day was Christmas.", ar: "دولار واحد وسبعة وثمانون سنتاً. كان هذا كل شيء. وكان اليوم التالي هو عيد الميلاد." },
            { en: "Della finished her cry and attended to her cheeks with the powder rag.", ar: "انتهت ديلا من بكائها واهتمت بوجنتيها بخرقة البودرة." },
            { en: "There were two possessions of the James Dillingham Youngs in which they both took a mighty pride.", ar: "كان هناك ممتلكان لعائلة جيمس ديلينجهام يونج يفتخران بهما بشدة." },
            { en: "One was Jim's gold watch that had been his father's and his grandfather's.", ar: "أحدهما كان ساعة جيمس الذهبية التي كانت لوالده وجده." },
            { en: "The other was Della's hair. It reached below her knee and made itself almost a garment for her.", ar: "والآخر كان شعر ديلا. كان يصل إلى أسفل ركبتها وكان بمثابة رداء لها." },
            { en: "So now Della's beautiful hair fell about her rippling and shining like a cascade of brown waters.", ar: "وهكذا سقط شعر ديلا الجميل حولها متموجاً ولامعاً كشلال من المياه البنية." },
            { en: "She went out and sold her hair for twenty dollars to buy a gift for Jim.", ar: "خرجت وباعت شعرها مقابل عشرين دولاراً لشراء هدية لجيم." },
            { en: "She found a platinum fob chain for Jim's watch, simple and chaste in design.", ar: "وجدت سلسلة بلاتينية لساعة جيم، بسيطة وعفيفة في التصميم." },
            { en: "When Jim came home, he looked at Della with a strange expression.", ar: "عندما عاد جيم إلى المنزل، نظر إلى ديلا بتعبير غريب." },
            { en: "He had sold his watch to buy a set of beautiful combs for her hair.", ar: "كان قد باع ساعته ليشتري مجموعة من الأمشاط الجميلة لشعرها." },
            { en: "They both gave up their greatest treasures to buy a gift for the other.", ar: "تخلى كلاهما عن أعظم كنوزهما لشراء هدية للآخر." },
            { en: "Of all who give and receive gifts, such as they are wisest. They are the magi.", ar: "من بين كل الذين يقدمون الهدايا ويتلقونها، أمثال هؤلاء هم الأحكم. إنهم المجوس." }
        ]
    },
    {
        id: 6,
        isInitial: true,
        title: "The Blue Carbuncle",
        author: "Arthur Conan Doyle",
        year: "1892",
        level: "Advanced",
        cover: "https://images.unsplash.com/photo-1512446816042-442d7100abd4?auto=format&fit=crop&w=800&q=80",
        description: "Sherlock Holmes solves the mystery of a stolen blue diamond found inside a Christmas goose.",
        descriptionAr: "شارلوك هولمز يحل لغز ماسة زرقاء مسروقة عُثر عليها داخل أوزة عيد الميلاد.",
        sentences: [
            { en: "On the second morning after Christmas, I called upon my friend Sherlock Holmes.", ar: "في الصباح الثاني بعد عيد الميلاد، زرت صديقي شارلوك هولمز." },
            { en: "He was lounging upon the sofa in a purple dressing-gown.", ar: "كان يستلقي على الأريكة مرتدياً ثوباً بنفسجياً." },
            { en: "Beside him was a battered old felt hat, much the worse for wear.", ar: "بجانبه كانت قبعة لباد قديمة مهترئة، في حالة سيئة جداً من كثرة الاستعمال." },
            { en: "I am examining a small matter,\" said Holmes, pointing at the hat.", ar: "أنا أفحص مسألة صغيرة\"، قال هولمز وهو يشير إلى القبعة." },
            { en: "This hat was found in the street along with a fat Christmas goose.", ar: "عُثر على هذه القبعة في الشارع مع أوزة عيد ميلاد سمينة." },
            { en: "Inside the goose, a wonderful blue diamond was discovered.", ar: "داخل الأوزة، تم اكتشاف ماسة زرقاء رائعة." },
            { en: "It was the famous Blue Carbuncle, stolen from the Countess of Morcar.", ar: "كانت الياقوتة الزرقاء الشهيرة، التي سُرقت من كونتيسة موركار." },
            { en: "Holmes began to trace the history of the goose to find the thief.", ar: "بدأ هولمز في تتبع تاريخ الأوزة للعثور على اللص." },
            { en: "He used his brilliant powers of deduction to solve the mystery.", ar: "استخدم قواه العبقرية في الاستنتاج لحل اللغز." },
            { en: "It is a wicked world,\" said Holmes, \"and when a clever man turns to crime, it is the worst of all.", ar: "إنه عالم شرير\"، قال هولمز، \"وعندما يتحول رجل ذكي إلى الجريمة، يكون ذلك الأسوأ على الإطلاق." },
            { en: "In the end, the mystery was solved and justice was served.", ar: "في النهاية، تم حل اللغز وتحققت العدالة." }
        ]
    }
];
